config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :questions do
    resources :answers do
      member do
        post :marked_useful 
      end 
    end
  end
  

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  acts_as_taggable
  validates :body, presence: true
  scope :order_by_created_at, -> { order(created_at: :desc) }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: [:show]
  layout "admin"

  def index
    @questions = current_user.questions.order_by_created_at
  end

  def show
    @answer = current_user.answers.build
  end

  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(question_param)
    if @question.save
      flash[:notice] = "Question submitted successfully"
      redirect_to questions_path
    else
      flash[:error] = @question.errors.full_messages
      render "new"
    end
  end

  private

  def find_question
    @question = Question.where(id: params[:id]).first
    unless @question.present?
      flash[:alert] = "Question not found"
      redirect_to questions_path
    end
  end

  def question_param
    params.require(:question).permit(:body, :tag_list, :tag_list => [])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def get_tags(question)
    raw question.tag_list.map { |t| link_to t }.join(', ')
  end
end

app/views/questions/_form.html.erb
<div class="col-lg-12">
  <%= form_for(@question, url: questions_path, html: { method: :post }) do |f| %>
    <div class="table-responsive"> 
      <table class="table table-bordered table-hover">
        <tr>
          <div class="form-group">
            <label class="col-sm-2 control-label" for="content">
              Question
            </label>
            <div class="col-sm-10">
              <%= f.text_area :body, label: false, rows: '10', :class => "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 margin_top">
              <%= f.label :tag_list, "Tags (separated by commas)" %><br /> 
            </div>
            <div class="col-sm-10 margin_top">
              <%= f.text_field :tag_list, class: "tag_width" %>
            </div>
          </div>
        </tr>
      </table>
      <%= f.submit "Submit Question", class: "btn btn-default" %> &nbsp
      <button type="reset" class="btn btn-default">Reset Button</button>
    </div>
  <% end %>
</div>

app/views/questions/_questions_index.html.erb
<div class="table-responsive">   
  <table class="table table-bordered table-hover table-striped">
    <thead>
      <tr>
        <th class="col-sm-9">Question</th>
        <th class="col-sm-2">Tags</th>
        <th colspan="1"><center></center></th> 
      </tr>
    </thead>            
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.body %></td>
        <td><%= get_tags(question) %></td>  
        <td><%= link_to "View", question_path(question.id) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/questions/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          My Questions
          <small>Welcome</small>
        </h1>
        <ol class="breadcrumb">
          <li>  
            <%= link_to " Ask Question", new_question_path, class: "glyphicon glyphicon-th-list" %>
          </li>
        </ol>
        <div id="questions_index">
          <%= render 'questions_index' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Ask Question
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="glyphicon glyphicon-arrow-left"></i> <%= link_to "Back", :back %>
          </li>
        </ol>
      </div>
    </div>
    <div class="row">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row set_page_size">
      <div class="col-lg-12">
        <h1 class="page-header">
          Question
          <small>Welcome</small>
        </h1>
        <ol class="breadcrumb">
          <li>  
            <%= link_to " Back", :back %>
          </li>
        </ol>
        <div>
          <div class="form-group">
            <label class="col-sm-2 control-label">
              <%= @question.user.try(:username) || "Guest user" %>
            </label>
            <div class="col-sm-10">
              <%= @question.body %>
            </div>
            <% if @question.tag_list.present? %>
              Tags: <%= get_tags(@question) %>
            <% end %>
          </div>
          <div class="form-group">
            <% if @question.answers.present? %>
              <label class="control-label">
                Answers
              </label>
              <div>
                <% @question.answers.order_by_created_at_asc.each do |answer| %>
                  <div class="comment_border">
                    <p class="breadcrumb"><b><%= answer.user.try(:username) || "Guest User" %></b></p>
                    <p><%= answer.body %></p></br>
                    <% if @question.user_id == current_user.id %>
                      <% unless answer.marked_useful %>  
                        <%= button_to "+1 to user", marked_useful_question_answer_path(question_id: @question.id, id: answer.id), :method => "post", class: "btn-success btn-xs" %>    
                        <% else %>
                          <%= button_to "-1 to user", marked_useful_question_answer_path(question_id: @question.id, id: answer.id), :method => "post", class: "btn-danger btn-xs" %>    
                        <% end %>
                      <% end %>
                  </div><br />
                <% end %>
              </div>
            <% end %>
          </div>
          <div>
            <div class="col-lg-12 margin_top">
              <%= form_for(@answer, url: question_answers_path(question_id: @question.id), html: { method: :post }) do |f| %>
                <div class="table-responsive"> 
                  <table class="table table-bordered table-hover">
                    <tr>
                      <div class="form-group">
                        <label class="col-sm-2 control-label" for="content">
                          Post your Answer
                        </label>
                        <div class="col-sm-10">
                          <%= f.text_area :body, label: false, rows: '3', :class => "form-control" %>
                        </div>
                      </div>
                    </tr>
                  </table>
                  <%= f.submit "Submit Answer", class: "btn btn-default" %> &nbsp
                  <button type="reset" class="btn btn-default">Reset Button</button>
                </div>
              <% end %>
            </div>  
          </div>
        </div>
      </div>
    </div>
  </div>
</div>