config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :questions do
    resources :answers do
      member do
        post :marked_useful 
      end 
    end
  end
  

end

app/views/layouts/_devise_flash_message.html.erb
<% if devise_error_messages!.present? %>
  <div class="alert alert-danger">
    <%= devise_error_messages! %> 
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% if flash.present? %>
  <% flash.each do |key, value| %>
    <% if flash.now[:error].present? %>
      <div class="alert alert-danger">
      <ul>
        <% value.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% else %>
      <div class="alert alert-success  fade in">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= value %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>QA Portal</title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
</head>
<body>
  <div id="wrapper">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        </button>
        <a class="navbar-brand" href="#">Welcome to QNA Portal</a>
      </div>
      <ul class="nav navbar-right top-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>User<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Profile", edit_user_registration_path, class: "fa fa-fw fa-user" %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "fa fa-fw fa-power-off" %>
            </li>
          </ul>
        </li>
      </ul>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li class="active">
            <%= link_to " Home", dashboard_index_path, class: "glyphicon glyphicon-home" %>
          </li>
          <li>
            <%= link_to " All Questions", dashboard_index_path, class: "glyphicon glyphicon-calendar" %>
          </li>
          <li>
            <%= link_to " My Questions", questions_path, class: "glyphicon glyphicon-calendar" %>
          </li>
          <li>
            <%= link_to " My Answers", question_answers_path(question_id: current_user.id), class: "glyphicon glyphicon-calendar" %>
          </li>
          <li>
            <%= link_to " Points", "#", class: "glyphicon glyphicon-calendar" %>
          </li>
        </ul>
      </div>
    </nav>
    <div id="flash_message">
      <%= render :partial => "layouts/flash_message" %>
    </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ask Questions</title>
    <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'login', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <div class="top-content">
      <div class="inner-bg">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-sm-offset-2 text">
              <h1><strong>Ask</strong> Questions</h1>
            </div>
          </div>
          <%= yield %>
          <div class="row">
            <div class="col-sm-6 col-sm-offset-3 social-login">
              <h3>...or login with:</h3>
              <div class="social-login-buttons">
                <a class="btn btn-link-2" href="#">
                  <i class="fa fa-facebook"></i> Facebook
                </a>
                <a class="btn btn-link-2" href="#">
                  <i class="fa fa-twitter"></i> Twitter
                </a>
                <a class="btn btn-link-2" href="#">
                  <i class="fa fa-google-plus"></i> Google Plus
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>        
    </div>
  </body>
</html>